workspace:
  base: /root
  path: account-sidecar

pipeline:
  deps:
    image: node:6-alpine
    pull: true
    commands:
      - yarn

  lint:
    image: node:6-alpine
    pull: true
    commands:
      - yarn lint

  build:
    image: node:6-alpine
    pull: true
    commands:
      - yarn build

  deploy:
    image: plugins/s3
    bucket: core-cdn
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key, s3_endpoint ]
    source: dist/**/*
    target: /account
    strip_prefix: dist/
    path_style: true
    exclude:
      - "**/*.json"
    when:
      event: [push, tag]
