workspace:
  base: /root
  path: account-sidecar

pipeline:
  restore_cache:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key, s3_endpoint ]
    restore: true
    path: path/account-sidecar
    filename: /vendor.tgz

  deps:
    image: node:6-alpine
    pull: true
    commands:
      - yarn

  rebuild-cache:
    group: cache
    image: plugins/s3-cache:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key, s3_endpoint ]
    rebuild: true
    path: drone/account-sidecar
    filename: /vendor.tgz
    mount:
      - node_modules
      - /root/.yarn
    when:
      event: push

  flush-cache:
    group: cache
    image: plugins/s3-cache:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key, s3_endpoint ]
    flush: true
    flush_age: 7
    flush_path: drone/account-sidecar/vendor.tgz

  lint:
    group: test
    image: node:6-alpine
    pull: true
    commands:
      - yarn lint

  build:
    group: test
    image: node:6-alpine
    pull: true
    commands:
      - yarn build

  deploy:
    image: plugins/s3
    bucket: core-cdn
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key, s3_endpoint ]
    source: dist/**/*
    target: /account
    strip_prefix: dist/
    path_style: true
    exclude:
      - assets.json
    when:
      event: [push, tag]
